### ISSUE TITLE
WordPress.org Assets

### ISSUE THREAD

**Issue by seb86** [seb86/Storefront-Beta-Tester#1]
@jameskoster Could you please provide me the header template you use for the other storefront extensions on WordPress.org so that I can create one for this plugin?

**Comment by jameskoster** [comment]
Sure; https://cloudup.com/csrLmOQjdxv

**Comment by seb86** [comment]
@jameskoster Thank you.

**Comment by BurlesonBrad** [comment]
I've had both the WooCommerce updater and the Storefront updater running for a few days now.  
I've even changed the 60*60*6 to look for updates sooner than the 6 hour mark ~ still nothing.
These are all on totally clean, local installations running nothing more than WP, WC, & SF

Would anyone know why these aren't showing any updates at all? Any ideas?
