### ISSUE TITLE
ThemeURI undefined

### ISSUE THREAD

**Issue by seb86** [seb86/Storefront-Beta-Tester#4]
The theme update is there but due to this error it won't show up for me to select and update.

> Notice: Undefined index: ThemeURI in S:\xampp\htdocs\dev\wp-content\plugins\storefront-beta-tester\storefront-beta-tester.php on line 88

**Comment by seb86** [comment]
Screenshot of theme update for Storefront Beta not showing. https://cloudup.com/cl4DV8WAe1Z

**Comment by seb86** [comment]
Turns out ThemeURI is not used unlike a plugin uses PluginURI so I replaced it with "http://www.woothemes.com/storefront" but still no theme shows up.

**Comment by seb86** [comment]
This issue is related to #3

**Comment by seb86** [comment]
I'm not sure if this is required but so far it still remains to return blank even though the data is there. Not sure why at the moment.

**Comment by seb86** [comment]
@jameskoster and  @BurlesonBrad Can you examine and test the beta tester plugin and see what is still missing or incorrect in the code for it to work. I have made a few improvements but still unable to actually select the theme to update.

[See screenshot](https://cloudup.com/cl4DV8WAe1Z) for what it is currently doing.

**Comment by seb86** [comment]
@jameskoster and @BurlesonBrad Never mind. I have found the last remaining issue and have fixed it.

**Comment by BurlesonBrad** [comment]
Sorry, I was in a conference call. Lemme double check it

**Comment by seb86** [comment]
@BurlesonBrad No need. I got it to work.
